Model description
analysiscenter/radial pull request #9
Opened 2019-04-19 13:39 UTC by dmylzenova

2019-04-19 13:49 UTC, anton-br requested changes

2019-04-19 13:49 UTC, anton-br commented on research/model_description.ipynb
>      "    print(\"* '{}'\\n   shape - {}, dtype - {}, data - {!r:.40}{}\".format(data, example_data[data].shape, example_data[data].dtype, example_data[data], ('...])' if data!='target' else '')))"
example_data doesn't exist now

2019-04-19 13:49 UTC, anton-br commented on research/model_description.ipynb
> +    "new_log_data = np.load('../radial/tests/data/new_log.npz')\n",
I think it will be better if you change path to'/path/to/data/file.npz' or smth like this.

2019-04-19 13:49 UTC, anton-br commented on research/model_description.ipynb
> +    "np.savez('../radial/tests/data/new_log.npz', time=example_data['time'], derivative=example_data['derivative'])"
here too

2019-04-19 13:49 UTC, anton-br commented on research/model_description.ipynb
> +    "model_path = '../saved_model/'"
delete points from the path

2019-04-19 13:49 UTC, anton-br commented on research/model_description.ipynb
> +    "plt.scatter(time[0], derivative[0])\n",
please, draw a dotted line and make it blue. Because all predictions on the graph below using this style

2019-04-19 13:49 UTC, anton-br commented
and fix pylit please

2019-04-21 11:44 UTC, dmylzenova commented on research/model_description.ipynb
> +    "np.savez('../radial/tests/data/new_log.npz', time=example_data['time'], derivative=example_data['derivative'])"
fixed all comments

2019-04-22 08:42 UTC, anton-br requested changes
> first cell ```print('smt {0!r:.50}'.format(example_data['time']))```
Do we really need this line? In the line below you do the same.

> second cell ```example_data = np.load('../radial/tests/data/rr_0.npz')```
Fix path

2019-04-24 07:37 UTC, merged